[package]
name = "i3lock-fancy-acceptably-fast"
version = "0.1.0"
edition = "2021"
authors = ["urlordjames <32751441+urlordjames@users.noreply.github.com>"]
license = "GPL-3.0+"

[dependencies]
ocl = "0.19"
xcb = "1.3"
